MODEL:
  BACKBONE:
    PRETRAIN_PATH: 'pretrained/vgg16_caffe-292e1171.pth'
  HEADS:
    NUM_CLASSES: 21
  DEVICE_ID: '("0, 1")'

INPUT:
  SIZE_TRAIN: [300, 300]
  SIZE_TEST: [300, 300]

DATA:
  ROOT: '/home/workspace/merlin/data_dirs/VOCdevkit/VOC2007'
#  ROOT: '/home/workspace/data_dirs/VOCdevkit/VOC2007'
  VALROOT: '/home/workspace/merlin/data_dirs/VOCdevkit/VOCdevkit/'

SOLVER:
  BATCH_SIZE: 16
  CHECKPOINT_PERIOD: 5
  EVAL_PERIOD: 20
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 400
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: [40000, 50000]
  GAMMA: 0.1

OUTPUT_DIR: "output/with_val"
RESUME: False
LOAD_FROM: "output/myanchor/epoch_395.pth"
TEST:
  IMS_PER_BATCH: 64

