MODEL:
  BACKBONE:
    PRETRAIN_PATH: 'pretrained/vgg16_caffe-292e1171.pth'
  HEADS:
    NUM_CLASSES: 21
  DEVICE_ID: '("1")'

INPUT:
  SIZE_TRAIN: [300, 300]
  SIZE_TEST: [300, 300]

DATA:
  ROOT: '/home/workspace/merlin/data_dirs/VOCdevkit/VOC2007'
#  ROOT: '/home/workspace/data_dirs/VOCdevkit/VOC2007'
  VALROOT: '/home/workspace/merlin/data_dirs/VOCdevkit/VOCdevkit/'

SOLVER:
  BATCH_SIZE: 16
  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 400
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  STEPS: [50000, 60000]
  GAMMA: 0.1

  WARMUP: True
  WARMUP_ITERS: 1500

OUTPUT_DIR: "output/bs16_SGD_all_trans_mymodel_changed_warmup"
RESUME: False
LOAD_FROM: "output/bs16_SGD_all_trans_model/epoch_80.pth"
TEST:
  IMS_PER_BATCH: 64

