MODEL:
  BACKBONE:
    PRETRAIN_PATH: 'pretrained/vgg16_caffe-292e1171.pth'
  HEADS:
    NUM_CLASSES: 21
  DEVICE_ID: '("1")'

INPUT:
  SIZE_TRAIN: [300, 300]
  SIZE_TEST: [300, 300]

DATA:
  ROOT: '/home/workspace/merlin/data_dirs/VOCdevkit/VOC2007'

SOLVER:
  BATCH_SIZE: 32
  CHECKPOINT_PERIOD: 5
  EVAL_PERIOD: 10
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 400
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: [400000, 500000, 600000]
  GAMMA: 0.1

OUTPUT_DIR: "output/myanchor"
LOAD_FROM: "output/baseline/epoch_2.pth"


