MODEL:
  NAME: 'SSD'
  BACKBONE:
    NAME: 'SSDVGG'
    PRETRAIN_PATH: 'pretrained/vgg16_caffe-292e1171.pth'
  HEADS:
    NAME: 'SSDHead'
    NUM_CLASSES: 81
  LOSSES:
    NAME: 'SSDLoss'
  DEVICE_ID: '("3")'

INPUT:
  SIZE_TRAIN: 300
  SIZE_TEST: 300

DATA:
  NAME: 'COCO'
  TRAINROOT: '/workspace/data_dir/COCO/coco'
  VALROOT: '/workspace/data_dir/COCO/coco'

SOLVER:
  BATCH_SIZE: 32
  VAL_BATCH_SIZE: 48
  CHECKPOINT_PERIOD: 50
  EVAL_PERIOD: 50
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 1000
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  STEPS: [60000]
  GAMMA: 0.1

  WARMUP: True
  WARMUP_ITERS: 1000

DISTRIBUTE: True
LAUNCH: False
VARIRANCE: [0.1, 0.2]
OUTPUT_DIR: "output/cocotrainval35k_bs32_singleGPU"

RESUME: False
LOAD_FROM: "output/bs16_SGD_all_trans_model/epoch_80.pth"

