MODEL:
  NAME: 'SSD'
  BACKBONE:
    NAME: 'SSDVGG'
    PRETRAIN_PATH: 'pretrained/vgg16_caffe-292e1171.pth'
  HEADS:
    NAME: 'SSDHead'
    NUM_CLASSES: 81
  LOSSES:
    NAME: 'SSDLoss'
  DEVICE_ID: '("1,2")'

INPUT:
  SIZE_TRAIN: 300
  SIZE_TEST: 300

DATA:
  NAME: 'COCO'
  TRAINROOT: '/home/data/COCO/coco'
  VALROOT: '/home/data/COCO/coco'

SOLVER:
  BATCH_SIZE: 32
  VAL_BATCH_SIZE: 72
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 10
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 1000
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  STEPS: [160000, 200000]
  GAMMA: 0.1

  WARMUP: True
  WARMUP_ITERS: 1000

DISTRIBUTE: False
LAUNCH: False
VARIRANCE: [0.1, 0.2]
OUTPUT_DIR: "output/temp"

RESUME: False
LOAD_FROM: "output/cocotrainval35k_bs32_singleGPU_evalfixed/epoch_100.pth"

