MODEL:
  NAME: 'SSD'
  BACKBONE:
    NAME: 'SSDVGG'
    PRETRAIN_PATH: '/root/.cache/torch/hub/checkpoints/vgg16_caffe-292e1171.pth'
  HEADS:
    NAME: 'SSDHead'
    NUM_CLASSES: 21
  LOSSES:
    NAME: 'SSDLoss'
  DEVICE_ID: '("2, 3")'

INPUT:
  SIZE_TRAIN: 300
  SIZE_TEST: 300

DATA:
  TRAINROOT: '/workspace/data_dir/VOC2007'
#  ROOT: '/home/workspace/data_dirs/VOCdevkit/VOC2007'
  VALROOT: '/workspace/data_dir/VOC2007'

SOLVER:
  BATCH_SIZE: 64
  VAL_BATCH_SIZE: 48
  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 5
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  STEPS: [5000, 6000]
  STEPS_EPOCH: [80, 110 ]
  GAMMA: 0.1

  WARMUP: True
  WARMUP_ITERS: 300
  LR_RATIO: 0.001

DISTRIBUTE: True
LAUNCH: True
VARIRANCE: [0.1, 0.2]
OUTPUT_DIR: "output/voc_ddp"

RESUME: False
LOAD_FROM: "output/bs16_SGD_all_trans_mymodel_changed_warmup/epoch_219.pth"

